["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "./src/account.cairo",
]
demo_token = [
    "./src/demo_token.cairo",
]

